#!/bin/bash
# shellcheck disable=SC1091,SC2164,SC2034,SC1072,SC1073,SC1009
if [[ "$EUID" -ne 0 ]]; then
    echo "Run this as root"
    exit
fi
apt update
apt install -y apache2 mariadb-server mariadb-client wget unzip php php-common php-mysql php-xml php-xmlrpc php-curl php-gd php-imagick php-cli php-dev php-imap php-mbstring php-soap php-zip php-intl
systemctl enable apache2
systemctl start apache2
systemctl enable --now mariadb
mysql_secure_installation
wget https://wordpress.org/latest.zip
unzip latest.zip
cd wordpress
cp -r * /var/www/html
cd /var/www/html
rm -rf index.html
apt install -y php-mysql php-cgi php-cli php-gd -y
chown -R www-data:www-data /var/www/
read -p "Enter the name of the new database: " NEW_DB
read -p "Enter the name of the new user: " NEW_USER
read -sp "Enter the password for the new user: " NEW_USER_PASSWORD
echo
mysql -u root -p <<EOF
CREATE DATABASE $NEW_DB;
CREATE USER '$NEW_USER'@'%' IDENTIFIED BY '$NEW_USER_PASSWORD';
GRANT ALL PRIVILEGES ON $NEW_DB.* TO '$NEW_USER'@'%';
FLUSH PRIVILEGES;
EOF
systemctl restart apache2
