#!/bin/bash
# shellcheck disable=SC1091,SC2164,SC2034,SC1072,SC1073,SC1009

if [[ "$EUID" -ne 0 ]]; then
    echo "Run this as root"
    exit
fi

install_package() {
    PACKAGE=$1
    dpkg -s "$PACKAGE" &> /dev/null

    if [ $? -eq 0 ]; then
        echo "$PACKAGE is already installed."
    else
        echo "$PACKAGE is not installed."
        while true; do
            read -p "Do you want to install $PACKAGE? (yes/no) " yn
            case $yn in
                yes ) apt install -y "$PACKAGE"; break;;
                no ) echo "Cannot proceed without $PACKAGE."; exit;;
                * ) echo "Please answer yes or no.";;
            esac
        done
    fi
}

download_file() {
    URL=$1
    FILE=$(basename "$URL")

    if [ -f "$FILE" ]; then
        echo "$FILE already exists."
        while true; do
            read -p "Do you want to download and replace $FILE? (yes/no) " yn
            case $yn in
                yes ) wget -O "$FILE" "$URL"; break;;
                no ) echo "Using existing $FILE."; break;;
                * ) echo "Please answer yes or no.";;
            esac
        done
    else
        wget "$URL"
    fi
}

apt update

install_package "apache2"
install_package "mariadb-server"
install_package "mariadb-client"
install_package "php"
install_package "php-common"
install_package "php-mysql"
install_package "php-xml"
install_package "php-xmlrpc"
install_package "php-curl"
install_package "php-gd"
install_package "php-imagick"
install_package "php-cli"
install_package "php-dev"
install_package "php-imap"
install_package "php-mbstring"
install_package "php-soap"
install_package "php-zip"
install_package "php-intl"
install_package "wget"
install_package "unzip"

systemctl enable apache2
systemctl start apache2

systemctl enable --now mariadb

mysql_secure_installation

download_file "https://wordpress.org/latest.zip"
unzip -o latest.zip -d wordpress

if [ -d "/var/www/html/wp-includes" ]; then
    echo "WordPress is already installed in /var/www/html."
    while true; do
        read -p "Do you want to overwrite the existing WordPress installation? (yes/no) " yn
        case $yn in
            yes ) rm -rf /var/www/html/*; cp -r wordpress/wordpress/* /var/www/html; break;;
            no ) echo "Skipping WordPress installation."; break;;
            * ) echo "Please answer yes or no.";;
        esac
    done
else
    cp -r wordpress/wordpress/* /var/www/html
fi

chown -R www-data:www-data /var/www/html

read -p "Enter the name of the new database: " NEW_DB
read -p "Enter the name of the new user: " NEW_USER
read -sp "Enter the password for the new user: " NEW_USER_PASSWORD
echo

mysql -u root -p <<EOF
CREATE DATABASE $NEW_DB;
CREATE USER '$NEW_USER'@'%' IDENTIFIED BY '$NEW_USER_PASSWORD';
GRANT ALL PRIVILEGES ON $NEW_DB.* TO '$NEW_USER'@'%';
FLUSH PRIVILEGES;
EOF

systemctl restart apache2

echo "Installation and configuration complete!"
