#!/bin/bash
# shellcheck disable=SC1091,SC2164,SC2034,SC1072,SC1073,SC1009
if [[ "$EUID" -ne 0 ]]; then
    echo "Run this as root"
    exit
fi

sudo apt update
sudo apt install -y apache2 mariadb-server mariadb-client php php-common php-mysql php-xml php-xmlrpc php-curl php-gd php-imagick php-cli php-dev php-imap php-mbstring php-soap php-zip php-intl wget unzip

sudo systemctl enable --now apache2
sudo systemctl enable --now mariadb
mysql_secure_installation

check_wordpress_files() {
    if [[ -f "/var/www/html/wp-config.php" && -f "/var/www/html/index.php" ]]; then
        return 0
    else
        return 1
    fi
}

install_wordpress() {
    wget https://wordpress.org/latest.zip
    sudo unzip latest.zip
    cd wordpress
    sudo cp -r * /var/www/html
    cd /var/www/html
    sudo rm -rf index.html
    sudo chown -R www-data:www-data /var/www/
}

echo "Choose an option for WordPress installation:"
echo "1) I already have WordPress"
echo "2) I want to install WordPress"
read -p "Enter your choice [1 or 2]: " WP_CHOICE

case $WP_CHOICE in
    1)
        if check_wordpress_files; then
            echo "WordPress files found. Proceeding to the next step."
        else
            echo "You don't have the required WordPress files. Please install WordPress."
            WP_CHOICE=2
        fi
        ;;
    2)
        if check_wordpress_files; then
            echo "You already have WordPress installed."
            echo "1) Download and replace"
            echo "2) Skip this step"
            read -p "Enter your choice [1 or 2]: " REPLACE_CHOICE
            case $REPLACE_CHOICE in
                1)
                    echo "Downloading and replacing WordPress files..."
                    install_wordpress
                    ;;
                2)
                    echo "Skipping WordPress installation."
                    ;;
                *)
                    echo "Invalid choice. Skipping WordPress installation."
                    ;;
            esac
        else
            echo "Installing WordPress..."
            install_wordpress
        fi
        ;;
    *)
        echo "Invalid choice. Exiting."
        exit 1
        ;;
esac

# Database setup
read -p "Enter the name of the new database: " NEW_DB
read -p "Enter the name of the new user: " NEW_USER
read -sp "Enter the password for the new user: " NEW_USER_PASSWORD
echo
mysql -u root -p <<EOF
CREATE DATABASE $NEW_DB;
CREATE USER '$NEW_USER'@'%' IDENTIFIED BY '$NEW_USER_PASSWORD';
GRANT ALL PRIVILEGES ON $NEW_DB.* TO '$NEW_USER'@'%';
FLUSH PRIVILEGES;
EOF
sudo systemctl restart apache2
